CREATE TABLE SCHEDULES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    client_id BIGINT NOT NULL,
    UNIQUE KEY UK_SCHEDULE_INTERVAL (start_at, end_at),
    CONSTRAINT FK_CLIENTS_SCHEDULES FOREIGN KEY (client_id) REFERENCES CLIENTS(id)
);